# -*- coding: utf-8 -*-
# =============================================================================
# مصدر نصوص الواجهة بالعربية والإنجليزية.
# شغّل:  python3 tool/strings.py   لتوليد lib/l10n/app_ar.arb و app_en.arb
# ثم flutter gen-l10n (أو أي flutter run/build يولّدها تلقائياً).
# لإضافة نص: أضف سطراً (المفتاح، العربي، الإنجليزي) ثم أعد تشغيل السكربت.
# =============================================================================
import json, re, os

S = [
# ---- عام ----
('appName', 'دفتري', 'Daftari'),
('save', 'حفظ', 'Save'),
('cancel', 'إلغاء', 'Cancel'),
('delete', 'حذف', 'Delete'),
('edit', 'تعديل', 'Edit'),
('confirm', 'تأكيد', 'Confirm'),
('back', 'رجوع', 'Back'),
('apply', 'تطبيق', 'Apply'),
('reset', 'إعادة ضبط', 'Reset'),
('undo', 'تراجع', 'Undo'),
('continueLabel', 'متابعة', 'Continue'),
('optional', 'اختياري', 'Optional'),
('today', 'اليوم', 'Today'),
('yesterday', 'أمس', 'Yesterday'),
('saved', 'تم الحفظ', 'Saved'),
('seeAll', 'عرض الكل', 'See all'),
('note', 'ملاحظة', 'Note'),
('date', 'التاريخ', 'Date'),
('amount', 'المبلغ', 'Amount'),
('account', 'الحساب', 'Account'),
('category', 'الفئة', 'Category'),
('name', 'الاسم', 'Name'),
('phone', 'رقم الجوال', 'Phone'),
('comingSoon', 'قريباً', 'Soon'),
('archivedBadge', 'مؤرشف', 'Archived'),
('defaultBadge', 'افتراضي', 'Default'),
('all', 'الكل', 'All'),
('more', 'المزيد', 'More'),
('noResults', 'لا توجد نتائج', 'No results'),
('password', 'كلمة المرور', 'Password'),
('passwordTooShort', '6 أحرف على الأقل', 'At least 6 characters'),
('areYouSure', 'هل أنت متأكد؟', 'Are you sure?'),
# ---- التنقل ----
('navHome', 'الرئيسية', 'Home'),
('navTransactions', 'المعاملات', 'Activity'),
('navDebts', 'الديون', 'Debts'),
('navMore', 'المزيد', 'More'),
('pressBackAgainToExit', 'اضغط رجوع مرة أخرى للخروج', 'Press back again to exit'),
# ---- الإعداد الأول ----
('chooseCurrency', 'اختر عملتك', 'Choose your currency'),
('currencyWarning', 'ستُستخدم في كل التطبيق ولا يمكن تغييرها لاحقاً', 'Used across the app and cannot be changed later'),
('searchCurrency', 'ابحث عن عملة', 'Search currency'),
('cloudBackupOptionalHint', 'اختياري — يمكن تفعيله لاحقاً من الإعدادات', 'Optional — enable it later from settings'),
('confirmCurrencyTitle', 'تأكيد عملة التطبيق', 'Confirm app currency'),
('confirmCurrencyBody', 'ستُسجَّل كل الحسابات والمعاملات والديون بهذه العملة.', 'All accounts, transactions and debts will be recorded in this currency.'),
('confirmCurrencyWarning', 'لا يمكن تغييرها بعد التأكيد', 'It cannot be changed after confirming'),
('confirmAndStart', 'تأكيد والبدء', 'Confirm & start'),
('backAndChange', 'رجوع وتغيير العملة', 'Back & change currency'),
('restoreExisting', 'لديك نسخة احتياطية؟ استعادة', 'Have a backup? Restore'),
# ---- الرئيسية ----
('greetingMorning', 'صباح الخير', 'Good morning'),
('greetingEvening', 'مساء الخير', 'Good evening'),
('totalBalance', 'إجمالي أرصدة الحسابات', 'Total balance'),
('monthIncome', 'دخل الشهر', 'Income'),
('monthExpense', 'مصروف الشهر', 'Expenses'),
('quickExpense', 'مصروف', 'Expense'),
('quickIncome', 'دخل', 'Income'),
('quickTransfer', 'تحويل', 'Transfer'),
('quickDebt', 'دين', 'Debt'),
('monthlyBudget', 'الميزانية الشهرية', 'Monthly budget'),
('budgetOf', '{spent} من {limit}', '{spent} of {limit}'),
('remainingForDays', 'متبقٍ {amount} لـ {days, plural, =0{اليوم} =1{يوم واحد} =2{يومين} few{{days} أيام} many{{days} يوماً} other{{days} يوم}}', '{amount} left for {days, plural, =0{today} =1{1 day} other{{days} days}}'),
('owedToMe', 'لي عند الناس', 'Owed to me'),
('iOwe', 'عليّ للناس', 'I owe'),
('recentTransactions', 'آخر المعاملات', 'Recent'),
('noTransactionsYet', 'لا توجد معاملات بعد. اضغط + لإضافة أول معاملة.', 'No transactions yet. Tap + to add your first one.'),
('hideBalances', 'إخفاء الأرصدة', 'Hide balances'),
# ---- المعاملات ----
('transactionsTitle', 'المعاملات', 'Transactions'),
('searchTransactions', 'ابحث بالاسم أو المبلغ', 'Search by name or amount'),
('addTransaction', 'إضافة معاملة', 'Add transaction'),
('editTransaction', 'تعديل معاملة', 'Edit transaction'),
('typeExpense', 'مصروف', 'Expense'),
('typeIncome', 'دخل', 'Income'),
('typeTransfer', 'تحويل', 'Transfer'),
('typeAdjustment', 'تسوية', 'Adjustment'),
('typeDebtOut', 'حركة دين — خرج', 'Debt movement — out'),
('typeDebtIn', 'حركة دين — دخل', 'Debt movement — in'),
('debtMovement', 'حركة دين', 'Debt movement'),
('fromAccount', 'من حساب', 'From account'),
('toAccount', 'إلى حساب', 'To account'),
('suggestedForCategory', 'مقترح: آخر حساب للفئة', 'Suggested: last used for category'),
('attachReceipt', 'إرفاق إيصال', 'Attach receipt'),
('receiptAttached', 'تم إرفاق الإيصال', 'Receipt attached'),
('removeReceipt', 'إزالة الإيصال', 'Remove receipt'),
('viewReceipt', 'عرض الإيصال', 'View receipt'),
('receiptCamera', 'الكاميرا', 'Camera'),
('receiptGallery', 'المعرض', 'Gallery'),
('chooseCategory', 'اختر فئة', 'Choose a category'),
('deleteTransactionTitle', 'حذف هذه المعاملة؟', 'Delete this transaction?'),
('deleteTransactionBody', '{description} — {amount}\nسيُعاد المبلغ إلى رصيد «{account}» تلقائياً.', '{description} — {amount}\nThe amount will be returned to “{account}” automatically.'),
('transactionDeleted', 'تم حذف المعاملة', 'Transaction deleted'),
('debtMovementHint', 'حركة دين تحرّك الرصيد ولا تُحتسب دخلاً ولا مصروفاً. تُعدَّل من ملف الشخص.', 'A debt movement changes the balance but is not income or expense. Edit it from the person’s profile.'),
('openPersonProfile', 'فتح ملف الشخص', 'Open profile'),
('budgetWarning', 'اقتربت من ميزانية «{category}»: {percent}%', 'Close to the “{category}” budget: {percent}%'),
('budgetExceeded', 'تجاوزت ميزانية «{category}» ({percent}%)', 'Over the “{category}” budget ({percent}%)'),
('filterTitle', 'فلترة المعاملات', 'Filter transactions'),
('period', 'الفترة', 'Period'),
('periodToday', 'اليوم', 'Today'),
('periodWeek', 'هذا الأسبوع', 'This week'),
('periodMonth', 'هذا الشهر', 'This month'),
('periodLast30', 'آخر 30 يوماً', 'Last 30 days'),
('periodLast3Months', 'آخر 3 أشهر', 'Last 3 months'),
('periodYear', 'هذه السنة', 'This year'),
('periodCustom', 'مخصص', 'Custom'),
('periodAll', 'كل الفترات', 'All time'),
('typeAndCategory', 'النوع والفئة', 'Type & category'),
('showDebtMovements', 'إظهار حركات الديون', 'Show debt movements'),
('showDebtMovementsHint', 'تظهر في السجل فقط ولا تدخل في الدخل والمصروف', 'Listed only — not counted as income or expense'),
('sort', 'الترتيب', 'Sort'),
('sortNewest', 'الأحدث أولاً', 'Newest first'),
('sortOldest', 'الأقدم أولاً', 'Oldest first'),
('sortAmountDesc', 'الأعلى مبلغاً', 'Highest amount'),
('sortAmountAsc', 'الأقل مبلغاً', 'Lowest amount'),
('allCategories', 'كل الفئات', 'All categories'),
('summaryIncome', 'دخل {amount}', 'Income {amount}'),
('summaryExpense', 'مصروف {amount}', 'Expense {amount}'),
# ---- الحسابات ----
('accountsTitle', 'الحسابات', 'Accounts'),
('totalActiveAccounts', 'إجمالي الحسابات النشطة', 'Total of active accounts'),
('activeAccountsCount', 'نشطة ({count})', 'Active ({count})'),
('archivedAccountsCount', 'المؤرشفة ({count})', 'Archived ({count})'),
('archivedSince', 'مؤرشف منذ {date}', 'Archived since {date}'),
('addAccount', 'إضافة حساب', 'Add account'),
('editAccount', 'تعديل الحساب', 'Edit account'),
('accountName', 'اسم الحساب', 'Account name'),
('accountType', 'نوع الحساب', 'Account type'),
('openingBalance', 'الرصيد الافتتاحي', 'Opening balance'),
('accountTypeCash', 'نقدي', 'Cash'),
('accountTypeBank', 'بنكي', 'Bank'),
('accountTypeWallet', 'محفظة', 'Wallet'),
('accountTypeSavings', 'توفير', 'Savings'),
('setAsDefault', 'تعيين كافتراضي', 'Set as default'),
('archive', 'أرشفة', 'Archive'),
('unarchive', 'رفع الأرشفة', 'Unarchive'),
('adjustBalance', 'تسوية الرصيد', 'Adjust balance'),
('adjustBalanceHint', 'أدخل الرصيد الفعلي وسيُسجَّل الفرق كمعاملة «تسوية» في السجل.', 'Enter the real balance; the difference is recorded as an “Adjustment”.'),
('actualBalance', 'الرصيد الفعلي', 'Actual balance'),
('archiveTitle', 'أرشفة «{name}»؟', 'Archive “{name}”?'),
('archiveBody', 'لن يظهر في الرئيسية ولا عند إضافة معاملة أو دين جديد. المعاملات السابقة تبقى كما هي وتظهر في التقارير.', 'It will be hidden from home and from new transactions or debts. Past records stay in history and reports.'),
('archiveHasBalance', 'رصيده الحالي {amount}', 'Current balance {amount}'),
('transferBalanceTo', 'تحويل الرصيد إلى', 'Transfer balance to'),
('transferAndArchive', 'تحويل الرصيد ثم الأرشفة', 'Transfer balance & archive'),
('newDefaultAccount', 'الحساب الافتراضي البديل', 'New default account'),
('recalculateBalances', 'إعادة احتساب الأرصدة', 'Recalculate balances'),
('recalculateDone', 'تمت المراجعة — صُحح {count} حساب', 'Audit done — {count} account(s) corrected'),
# ---- الديون ----
('debtsTitle', 'الديون', 'Debts'),
('debtsSubtitle', 'منفصلة عن الدخل والمصروف', 'Separate from income and expenses'),
('tabOwedToMe', 'لي', 'Owed to me'),
('tabIOwe', 'عليّ', 'I owe'),
('newDebt', 'دين جديد', 'New debt'),
('dueInDays', 'يستحق بعد {days, plural, =1{يوم} =2{يومين} few{{days} أيام} many{{days} يوماً} other{{days} يوم}}', 'Due in {days, plural, =1{1 day} other{{days} days}}'),
('overdueDays', 'متأخر {days, plural, =1{يوماً} =2{يومين} few{{days} أيام} many{{days} يوماً} other{{days} يوم}}', 'Overdue {days, plural, =1{1 day} other{{days} days}}'),
('dueToday', 'يستحق اليوم', 'Due today'),
('statusClosed', 'مغلق', 'Closed'),
('statusOverdue', 'متأخر', 'Overdue'),
('statusPartial', 'مسدَّد جزئياً', 'Partially paid'),
('statusOpen', 'مفتوح', 'Open'),
('ofTotal', 'من {amount}', 'of {amount}'),
('noDebts', 'لا توجد ديون مسجلة. سجّل ديناً لتتابع ما لك وما عليك.', 'No debts yet. Record one to track what you are owed and what you owe.'),
('directionOwedToMeHint', 'أقرضت / بعت بالآجل', 'I lent / sold on credit'),
('directionIOweHint', 'اقترضت / اشتريت بالآجل', 'I borrowed / bought on credit'),
('person', 'الشخص', 'Person'),
('choosePerson', 'اختر شخصاً', 'Choose a person'),
('fromContacts', 'من جهات الاتصال', 'From contacts'),
('addPerson', 'إضافة شخص', 'Add person'),
('dueDateOptional', 'الاستحقاق (اختياري)', 'Due date (optional)'),
('decreasesBalanceNotExpense', 'ينقص الرصيد — ليس مصروفاً', 'Decreases balance — not an expense'),
('increasesBalanceNotIncome', 'يزيد الرصيد — ليس دخلاً', 'Increases balance — not income'),
('remindBeforeDue', 'ذكّرني قبل الموعد بيوم', 'Remind me a day before'),
('saveDebt', 'حفظ الدين', 'Save debt'),
('editDebt', 'تعديل الدين', 'Edit debt'),
('deleteDebt', 'حذف الدين', 'Delete debt'),
('deleteDebtBody', 'يُحذف الدين مع قيده فيعود الحساب أو الدخل أو المصروف كما كان. (للديون المسجلة خطأً فقط.)', 'The debt and its entry are removed, restoring the account, income or expense. (For debts entered by mistake only.)'),
('remainingAmount', 'المتبقي الحالي: {amount}', 'Current remaining: {amount}'),
('fullRemaining', 'كامل المتبقي', 'Full remaining'),
('receivedIntoAccount', 'استلمتُ في', 'Received into'),
('paidFromAccount', 'دفعتُ من', 'Paid from'),
('profileOwedToMe', 'المتبقي لي عند {name}', '{name} owes me'),
('profileIOwe', 'المتبقي عليّ لـ {name}', 'I owe {name}'),
('paidAmount', 'المدفوع {amount}', 'Paid {amount}'),
('totalDebtsAmount', 'الإجمالي {amount}', 'Total {amount}'),
('dueOn', 'يستحق {date}', 'Due {date}'),
('statement', 'كشف', 'Statement'),
('timeline', 'الخط الزمني والرصيد بعد كل عملية', 'Timeline & balance after each entry'),
('balanceShort', 'الرصيد {amount}', 'Balance {amount}'),
('tlFrom', 'من {account}', 'from {account}'),
('tlInto', 'في {account}', 'into {account}'),
('tlIncomeCat', 'دخل {category}', '{category} income'),
('tlExpenseCat', 'مصروف {category}', '{category} expense'),
('tlNoAccount', 'بدون حساب', 'No account'),
('tlLedgerOnly', 'الدفتر فقط', 'Ledger only'),
('tlCancelled', 'ملغاة — لا تُحتسب', 'Cancelled — not counted'),
('paymentReceived', 'استلام', 'Received'),
('paymentMade', 'سداد', 'Paid'),
('editPerson', 'تعديل بيانات الشخص', 'Edit person'),
('searchPeople', 'بحث بالاسم أو الهاتف', 'Search by name or phone'),
('noDueDate', 'بدون موعد', 'No due date'),
('quickActions', 'الإجراءات السريعة', 'Quick actions'),
('closeLabel', 'إغلاق', 'Close'),
# ---- الديون: المصدر والاستلام والسداد والمسامحة ----
('sourceTitle', 'مصدر الدين', 'Where did this debt come from?'),
('sourceLoanOwed', 'أقرضته من حساب', 'I lent from an account'),
('sourceLoanOwe', 'اقترضتُ إلى حساب', 'I borrowed into an account'),
('sourceCreditSale', 'بعتُ له بالآجل', 'I sold on credit'),
('sourceCreditPurchase', 'اشتريتُ بالآجل', 'I bought on credit'),
('sourceOpening', 'دين سابق', 'Earlier debt'),
('sourceCreditSaleHint', 'يُسجَّل دخلاً ({category}) — بدون حركة حساب', 'Recorded as income ({category}) — no account movement'),
('sourceCreditPurchaseHint', 'يُسجَّل مصروفاً ({category}) — بدون حركة حساب', 'Recorded as an expense ({category}) — no account movement'),
('sourceOpeningHint', 'كان موجوداً قبل استخدام التطبيق — الدفتر فقط', 'Existed before using the app — ledger only'),
('loanOwedHint', 'ينقص رصيد الحساب — ليس مصروفاً', 'Reduces the account balance — not an expense'),
('loanOweHint', 'يزيد رصيد الحساب — ليس دخلاً', 'Increases the account balance — not income'),
('segOwedToMe', 'لي (عند شخص)', 'Owed to me'),
('segIOwe', 'عليّ (لشخص)', 'I owe'),
('deviceContacts', 'جهات الاتصال', 'Contacts'),
('labelLoanOwed', 'سلفة نقدية', 'Cash loan'),
('labelLoanOwe', 'اقتراض', 'Borrowed'),
('labelCreditSale', 'بيع بالآجل', 'Credit sale'),
('labelCreditPurchase', 'شراء بالآجل', 'Credit purchase'),
('labelOpening', 'دين سابق', 'Earlier debt'),
('debtLockedHint', 'عليه دفعات أو مسامحة: الاتجاه والمصدر والشخص مقفلة', 'It has payments or write-offs: direction, source and person are locked'),
('receiveAmount', 'استلام مبلغ', 'Receive payment'),
('payAmount', 'سداد مبلغ', 'Make payment'),
('receiveFrom', 'استلام مبلغ — {name}', 'Receive from {name}'),
('payTo', 'سداد مبلغ — {name}', 'Pay {name}'),
('remainingAfterReceive', 'المتبقي بعد الاستلام', 'Remaining after payment'),
('remainingAfterPay', 'المتبقي بعد السداد', 'Remaining after payment'),
('amountReceivedLabel', 'المبلغ المستلم', 'Amount received'),
('amountPaidLabel', 'المبلغ المدفوع', 'Amount paid'),
('autoDistTitle', 'التوزيع التلقائي — الأقدم أولاً', 'Automatic split — oldest first'),
('selectedDebtTitle', 'الدين المختار', 'Selected debt'),
('allocCloses', 'يُغلق', 'closes'),
('allocLeaves', 'يتبقى {amount}', '{amount} left'),
('chooseSpecificDebt', 'اختيار دين معيّن', 'Choose a specific debt'),
('autoDistribute', 'توزيع تلقائي', 'Automatic'),
('excessTitle', 'مبلغ زائد عن المتبقي', 'More than the remaining'),
('excessOwedToMe', 'الزائد {amount} — هل تسجّله ديناً عليك لـ {name}؟', 'The extra {amount} — record it as a debt you owe {name}?'),
('excessIOwe', 'الزائد {amount} — هل تسجّله ديناً لك على {name}؟', 'The extra {amount} — record it as a debt {name} owes you?'),
('recordExcess', 'تسجيل الزائد', 'Record the extra'),
('editAmount', 'تعديل المبلغ', 'Change amount'),
('excessNote', 'زيادة عن المستحق', 'Overpayment'),
('noOneOwesYou', 'لا توجد ديون مفتوحة لك عند أحد', 'No one owes you anything right now'),
('youOweNoOne', 'لا توجد ديون مفتوحة عليك', 'You don’t owe anyone right now'),
('distribution', 'تفصيل التوزيع', 'Breakdown'),
('cancelOperation', 'إلغاء العملية', 'Cancel operation'),
('cancelOperationBody', 'تُلغى كل دفعات العملية معاً ويُعكس أثرها على الحساب، وتبقى ظاهرة مشطوبة في الخط الزمني.', 'All payments in this operation are cancelled together and the account movement is reversed. They stay visible, struck through, in the timeline.'),
('cancelledBadge', 'ملغاة', 'Cancelled'),
('negativeCashWarning', 'تنبيه: رصيد «{account}» أصبح سالباً', 'Heads up: “{account}” balance is now negative'),
('forgiveRemaining', 'مسامحة بالمتبقي', 'Write off the rest'),
('forgivenRemaining', 'إعفاء من المتبقي', 'Mark the rest as forgiven'),
('forgiveBodyOwedToMe', 'يُغلق الدين ويُسجَّل المتبقي {amount} مصروفاً بفئة «مسامحة ديون». لا تتحرك أرصدة الحسابات.', 'Closes the debt and records the remaining {amount} as an expense under “Debt write-off”. No account balance changes.'),
('forgiveBodyIOwe', 'يُغلق الدين ويُسجَّل المتبقي {amount} دخلاً بفئة «إعفاء دين». لا تتحرك أرصدة الحسابات.', 'Closes the debt and records the remaining {amount} as income under “Debt relief”. No account balance changes.'),
('writeOffEntry', 'مسامحة', 'Written off'),
('forgivenEntry', 'إعفاء من الدين', 'Forgiven by creditor'),
('paymentRate', 'نسبة السداد {percent}%', 'Paid {percent}%'),
('writtenOffRate', 'مُسامَح {percent}%', 'Written off {percent}%'),
('netForYou', 'الصافي لصالحك {amount}', 'Net in your favor: {amount}'),
('netForThem', 'الصافي لصالح {name} {amount}', 'Net in {name}’s favor: {amount}'),
('netEven', 'الصافي متعادل', 'Net: even'),
('netInfoHint', 'معلومة فقط — لا يُخصم أحدهما من الآخر', 'For information only — the two are not offset'),
('balanceAfter', 'الرصيد بعد العملية: {amount}', 'Balance after: {amount}'),
('archivePerson', 'أرشفة الشخص', 'Archive person'),
('archivePersonBody', 'يختفي من القوائم والاختيار مع بقاء سجله كاملاً، ويمكن رفع أرشفته لاحقاً.', 'Hidden from lists and pickers; the full history is kept and you can unarchive later.'),
('deletePerson', 'حذف الشخص', 'Delete person'),
('deletePersonBody', 'لا توجد له أي حركة، وسيُحذف نهائياً.', 'This person has no activity and will be deleted permanently.'),
('personArchivedBanner', 'هذا الشخص مؤرشف', 'This person is archived'),
('peopleCount', '{count, plural, =0{لا أحد} =1{شخص واحد} =2{شخصان} few{{count} أشخاص} many{{count} شخصاً} other{{count} شخص}}', '{count, plural, =0{no one} =1{1 person} other{{count} people}}'),
('overdueCount', '{count, plural, =0{لا متأخرات} other{{count} متأخر}}', '{count, plural, =0{none overdue} =1{1 overdue} other{{count} overdue}}'),
('filterDebts', 'فلترة الديون', 'Filter debts'),
('statusFilter', 'الحالة', 'Status'),
('sortNearestDue', 'الأقرب استحقاقاً', 'Nearest due'),
('sortLastActivity', 'آخر حركة', 'Latest activity'),
('duplicatePerson', '«{name}» موجود، هل تقصده؟', '“{name}” already exists — did you mean them?'),
('useExisting', 'نعم، هو', 'Yes, that’s them'),
('reconcileOk', 'معادلة التطابق الشاملة متحققة ✓', 'Global reconciliation check passed ✓'),
('reconcileGap', 'تنبيه: فرق {amount} في معادلة التطابق — راجع البيانات', 'Warning: reconciliation gap of {amount} — please review your data'),
('archiveNeedsZero', 'لا يُؤرشف الحساب إلا ورصيده صفر — حوّل رصيده أولاً', 'An account can only be archived with a zero balance — transfer it first'),
# ---- كشف الحساب ----
('statementTitle', 'كشف حساب — {name}', 'Statement — {name}'),
('outputFormat', 'طريقة الإخراج', 'Output'),
('outputImage', 'صورة', 'Image'),
('outputImageHint', 'للكشف القصير', 'Short statements'),
('outputPdf', 'PDF', 'PDF'),
('outputPdfHint', 'للكشف الطويل', 'Long statements'),
('preview', 'معاينة', 'Preview'),
('whatsapp', 'واتساب', 'WhatsApp'),
('share', 'مشاركة', 'Share'),
('print', 'طباعة', 'Print'),
('closingBalance', 'الرصيد الختامي = المتبقي', 'Closing balance = balance due'),
('colMovement', 'الحركة', 'Movement'),
('statementShareText', 'كشف حساب {name} — دفتري', 'Statement for {name} — Daftari'),
('generatedAt', 'أُنشئ في', 'Generated'),
('noMovementsInPeriod', 'لا توجد حركات في هذه الفترة', 'No movements in this period'),
('description', 'البيان', 'Description'),
('balance', 'الرصيد', 'Balance'),
('dueFromPerson', 'المبلغ المستحق على {name}', 'Amount due from {name}'),
('dueToPerson', 'المبلغ المستحق لـ {name}', 'Amount due to {name}'),
# ---- التقارير ----
('reportsTitle', 'التقارير', 'Reports'),
('income', 'الدخل', 'Income'),
('expense', 'المصروف', 'Expenses'),
('net', 'الصافي', 'Net'),
('incomeVsExpense', 'الدخل مقابل المصروف', 'Income vs expenses'),
('expenseByCategory', 'المصروف حسب الفئة', 'Expenses by category'),
('incomeByCategory', 'الدخل حسب الفئة', 'Income by category'),
('reportsExcludedNote', 'حركات الديون والتسويات والتحويلات مستبعدة من هذه الأرقام.', 'Debt movements, adjustments and transfers are excluded.'),
('monthlyView', 'شهري', 'Monthly'),
('yearlyView', 'سنوي', 'Yearly'),
('reportTitle', 'تقرير دفتري', 'Daftari report'),
('month', 'الشهر', 'Month'),
('shareOfTotal', 'النسبة', 'Share'),
('transactions', 'المعاملات', 'Transactions'),
('type', 'النوع', 'Type'),
('export', 'تصدير', 'Export'),
# ---- الميزانية ----
('budgetTitle', 'الميزانية', 'Budget'),
('spentOfBudget', 'مصروف {month} من الميزانية', '{month} spending vs budget'),
('addBudget', 'إضافة ميزانية', 'Add budget'),
('editBudget', 'تعديل الميزانية', 'Edit budget'),
('budgetLimit', 'سقف الإنفاق الشهري', 'Monthly limit'),
('alertAtPercent', 'التنبيه عند {percent}%', 'Alert at {percent}%'),
('budgetOverBy', 'تجاوزت الميزانية بـ {amount}', 'Over budget by {amount}'),
('legendSafe', 'أقل من 75%', 'Under 75%'),
('legendWarning', '75–99%', '75–99%'),
('legendExceeded', 'تجاوز', 'Over'),
('noBudgets', 'لا توجد ميزانيات. أضف سقفاً لفئة لتتابع إنفاقك.', 'No budgets yet. Add a limit to a category to track spending.'),
('deleteBudget', 'حذف الميزانية', 'Delete budget'),
# ---- الفئات ----
('categoriesTitle', 'الفئات', 'Categories'),
('addCategory', 'إضافة فئة', 'Add category'),
('editCategory', 'تعديل الفئة', 'Edit category'),
('categoryName', 'اسم الفئة', 'Category name'),
('icon', 'الأيقونة', 'Icon'),
('color', 'اللون', 'Color'),
('expenseCategories', 'فئات المصروف', 'Expense categories'),
('incomeCategories', 'فئات الدخل', 'Income categories'),
# ---- الإعدادات ----
('settingsTitle', 'الإعدادات', 'Settings'),
('sectionCurrency', 'العملة', 'Currency'),
('appCurrencyLocked', 'عملة التطبيق (مقفلة)', 'App currency (locked)'),
('addCurrency', 'إضافة عملة جديدة', 'Add a currency'),
('sectionGeneral', 'عام', 'General'),
('defaultAccount', 'الحساب الافتراضي', 'Default account'),
('languageAndAppearance', 'اللغة والمظهر', 'Language & appearance'),
('language', 'اللغة', 'Language'),
('languageArabic', 'العربية', 'العربية'),
('languageEnglish', 'English', 'English'),
('followDevice', 'حسب الجهاز', 'System'),
('theme', 'المظهر', 'Theme'),
('themeLight', 'فاتح', 'Light'),
('themeDark', 'داكن', 'Dark'),
('arabicDigits', 'الأرقام الهندية (١٢٣)', 'Arabic-Indic digits (١٢٣)'),
('sectionSecurityData', 'الأمان والبيانات', 'Security & data'),
('appLock', 'قفل التطبيق بالبصمة / PIN', 'App lock (biometric / PIN)'),
('cloudBackup', 'النسخ السحابي', 'Cloud backup'),
('localBackup', 'تصدير / استيراد ملف محلي', 'Export / import local file'),
('deleteAllData', 'حذف جميع البيانات', 'Delete all data'),
('deleteAllDataBody', 'سيُحذف كل شيء نهائياً وتعود للإعداد الأول. هذه هي الطريقة الوحيدة لتغيير العملة.', 'Everything will be permanently deleted and you will return to setup. This is the only way to change the currency.'),
('sectionManage', 'الإدارة', 'Manage'),
('version', 'الإصدار {version}', 'Version {version}'),
('contactSupport', 'تواصل معنا', 'Contact us'),
('supportWhatsApp', 'واتساب', 'WhatsApp'),
('supportCall', 'اتصال', 'Call'),
('supportInstagram', 'إنستغرام', 'Instagram'),
('linkOpenFailed', 'تعذّر فتح الرابط', "Couldn't open the link"),
('developedByPrefix', 'تم التطوير من قبل', 'Developed by'),
('developerName', 'محمد المخلافي', 'Mohammed Al-Mekhlafi'),
('sectionData', 'البيانات', 'Data'),
('sectionSecurity', 'الأمان والنسخ الاحتياطي', 'Security & backup'),
('ePayments', 'الدفع الإلكتروني', 'Electronic payments'),
('underDevelopment', 'قيد التطوير', 'In development'),
('ePaymentsSoon', 'الدفع الإلكتروني قيد التطوير وسيتوفر قريباً', 'Electronic payments are in development and coming soon'),
('payLocalWallets', 'المحافظ المحلية', 'Local wallets'),
('payLocalWalletsHint', 'محافظ إلكترونية محلية', 'Local e-wallets'),
('payCards', 'فيزا / ماستركارد', 'Visa / Mastercard'),
('payCardsHint', 'بطاقات ائتمان وخصم', 'Credit and debit cards'),
('payOtherCards', 'بطاقات دفع أخرى', 'Other payment cards'),
('payOtherCardsHint', 'مدى وغيرها', 'Mada and others'),
# ---- الأمان ----
('lockedTitle', 'دفتري مقفل', 'Daftari is locked'),
('enterPin', 'أدخل رمز PIN', 'Enter your PIN'),
('wrongPin', 'رمز غير صحيح', 'Wrong PIN'),
('useBiometrics', 'استخدام البصمة / الوجه', 'Use biometrics'),
('unlockReason', 'افتح دفتري', 'Unlock Daftari'),
('verifyIdentity', 'تأكيد هويتك', "Verify it's you"),
('deleteAllDataReason', 'تأكيد حذف جميع البيانات', 'Confirm deleting all data'),
('disableLockReason', 'تأكيد إيقاف قفل التطبيق', 'Confirm turning off app lock'),
('changePinReason', 'تأكيد تغيير رمز PIN', 'Confirm changing your PIN'),
('createPin', 'أنشئ رمز PIN من 4 أرقام', 'Create a 4-digit PIN'),
('confirmPin', 'أعد إدخال الرمز للتأكيد', 'Re-enter to confirm'),
('pinMismatch', 'الرمزان غير متطابقين', 'PINs do not match'),
('biometricUnlock', 'الفتح بالبصمة / الوجه', 'Unlock with biometrics'),
('changePin', 'تغيير رمز PIN', 'Change PIN'),
('lockAfterHint', 'يُقفل التطبيق بعد دقيقة من الخروج منه', 'Locks one minute after leaving the app'),
# ---- النسخ الاحتياطي ----
('backupTitle', 'النسخ الاحتياطي', 'Backup'),
('cloudBackupOff', 'النسخ السحابي معطّل', 'Cloud backup is off'),
('cloudBackupOn', 'النسخ السحابي مفعّل', 'Cloud backup is on'),
('cloudBackupHint', 'بحسابك الشخصي، مشفّر، دون خوادم خاصة بالتطبيق', 'Your own account, encrypted, no app servers'),
('storageProvider', 'مزوّد التخزين (حسابك الشخصي)', 'Storage (your personal account)'),
('googleDrive', 'Google Drive', 'Google Drive'),
('iCloud', 'iCloud', 'iCloud'),
('appleDevicesOnly', 'لأجهزة Apple', 'Apple devices'),
('connected', 'متصل', 'Connected'),
('frequency', 'التكرار', 'Frequency'),
('daily', 'يومي', 'Daily'),
('weekly', 'أسبوعي', 'Weekly'),
('monthly', 'شهري', 'Monthly'),
('wifiOnly', 'النسخ عبر Wi-Fi فقط', 'Wi-Fi only'),
('encryptionInfo', 'تشفير النسخة AES-256', 'AES-256 encryption'),
('lastBackup', 'آخر نسخة: {date}', 'Last backup: {date}'),
('neverBackedUp', 'لم تُنسخ بعد', 'Never backed up'),
('backupNow', 'نسخ الآن', 'Back up now'),
('restore', 'استعادة', 'Restore'),
('backupPassword', 'كلمة مرور التشفير', 'Encryption password'),
('backupPasswordHint', 'تحتاجها لاستعادة النسخة على جهاز جديد. لا يمكن استرجاعها إن نسيتها.', 'Needed to restore on a new device. It cannot be recovered if forgotten.'),
('backupDone', 'تم النسخ بنجاح', 'Backup completed'),
('restoreDone', 'تمت الاستعادة بنجاح', 'Restore completed'),
('restoreConfirm', 'ستُستبدل كل البيانات الحالية بمحتوى النسخة. متابعة؟', 'All current data will be replaced by the backup. Continue?'),
('chooseBackup', 'اختر نسخة', 'Choose a backup'),
('exportLocalFile', 'تصدير ملف نسخة مشفّر', 'Export encrypted backup file'),
('importLocalFile', 'استيراد ملف نسخة', 'Import backup file'),
('noCloudBackups', 'لا توجد نسخ في السحابة', 'No cloud backups found'),
# ---- رسائل الأخطاء ----
('errInvalidAmount', 'أدخل مبلغاً أكبر من صفر', 'Enter an amount greater than zero'),
('errEmptyName', 'الاسم مطلوب', 'Name is required'),
('errInvalidPhone', 'رقم الجوال غير صحيح', 'Invalid phone number'),
('errContactArchived', 'الشخص مؤرشف — ارفع أرشفته أولاً', 'This person is archived — unarchive them first'),
('errInvalidDebtSource', 'مصدر الدين لا يناسب اتجاهه', 'This source does not match the debt direction'),
('errAccountRequired', 'اختر الحساب', 'Choose an account'),
('errDateInFuture', 'التاريخ لا يكون بعد اليوم', 'The date cannot be in the future'),
('errDueBeforeStart', 'تاريخ الاستحقاق قبل تاريخ الدين', 'The due date is before the debt date'),
('errPaymentBeforeDebt', 'التاريخ يسبق تاريخ الدين — غيّره أو اختر ديناً معيّناً', 'The date is before the debt date — change it or choose a specific debt'),
('errDebtHasMovements', 'على الدين دفعات أو مسامحة — ألغِ الدفعات أولاً', 'This debt has payments or a write-off — cancel the payments first'),
('errPaymentAlreadyCancelled', 'العملية ملغاة مسبقاً', 'This operation is already cancelled'),
('errAccountHasBalance', 'لا يُؤرشف الحساب إلا ورصيده صفر — حوّل رصيده أولاً', 'An account can only be archived with a zero balance — transfer it first'),
('errPersonHasBalance', 'لا يُؤرشف الشخص إلا ومتبقّيه صفر في الاتجاهين', 'A person can only be archived when nothing is owed either way'),
('errPersonHasMovements', 'للشخص حركات مسجلة — يمكن أرشفته فقط', 'This person has recorded activity — archive them instead'),
('errDuplicateAccountName', 'يوجد حساب بنفس الاسم', 'An account with this name exists'),
('errAccountArchived', 'الحساب مؤرشف — ارفع أرشفته أولاً', 'The account is archived — unarchive it first'),
('errCannotArchiveLast', 'لا يمكن أرشفة آخر حساب نشط', 'You cannot archive the last active account'),
('errMustChooseNewDefault', 'اختر حساباً افتراضياً بديلاً أولاً', 'Choose a new default account first'),
('errSameAccountTransfer', 'اختر حسابين مختلفين للتحويل', 'Choose two different accounts'),
('errCategoryKindMismatch', 'الفئة لا تناسب نوع المعاملة', 'The category does not match the type'),
('errCategoryRequired', 'اختر فئة', 'Choose a category'),
('errDebtMovementReadOnly', 'قيود الديون تُعدَّل من ملف الشخص', 'Debt entries are edited from the person’s profile'),
('errCannotMoveArchived', 'لا يمكن نقل معاملة من حساب مؤرشف أو إليه', 'Cannot move a transaction to or from an archived account'),
('errPaymentExceeds', 'المبلغ أكبر من المتبقي ({amount})', 'Amount exceeds the remaining ({amount})'),
('errDebtSettled', 'لا توجد ديون مفتوحة لهذه العملية', 'There is no open debt for this operation'),
('errDebtAmountBelowPaid', 'الأصل لا يقل عن المدفوع والمُسامَح ({amount})', 'The amount cannot be less than what was paid and written off ({amount})'),
('errCurrencyLocked', 'العملة مقفلة ولا يمكن تغييرها', 'The currency is locked'),
('errNotOnboarded', 'أكمل الإعداد الأول أولاً', 'Complete setup first'),
('errCategoryInUse', 'الفئة مستخدمة في معاملات ولا يمكن حذفها', 'The category is in use and cannot be deleted'),
('errNotFound', 'العنصر غير موجود', 'Item not found'),
('errBackupDecryption', 'كلمة المرور خاطئة أو الملف تالف', 'Wrong password or corrupted file'),
('errBackupInvalid', 'الملف ليس نسخة دفتري صالحة', 'Not a valid Daftari backup'),
('errNoConnection', 'لا يوجد اتصال — سيُعاد المحاولة لاحقاً', 'No connection — will retry later'),
('errCloudNotAuthorized', 'لم يتم منح الإذن لحساب التخزين', 'Storage account not authorized'),
('errUnexpected', 'حدث خطأ غير متوقع', 'Something went wrong'),
# ---- الإشعارات ----
('notifChannel', 'تذكير الديون', 'Debt reminders'),
('notifTitle', 'تذكير بدين', 'Debt reminder'),
('notifOwedToMe', 'غداً موعد استحقاق {amount} على {name}', '{name} owes you {amount}, due tomorrow'),
('notifIOwe', 'غداً موعد سداد {amount} لـ {name}', 'You owe {name} {amount}, due tomorrow'),
# ---- شاشات الترحيب ----
('introSkip', 'تخطي', 'Skip'),
('introNext', 'التالي', 'Next'),
('introStart', 'ابدأ الآن', 'Get started'),
('intro1Title', 'دفترك المالي في جيبك', 'Your finances in your pocket'),
('intro1Body', 'سجّل دخلك ومصروفك وتحويلاتك بين حساباتك في ثوانٍ وتابع ميزانيتك بألوان واضحة.', 'Record income, expenses and transfers between your accounts in seconds, and follow your budget in clear colors.'),
('intro2Title', 'ديونك منظمة… وحقك محفوظ', 'Debts organized… your rights protected'),
('intro2Body', 'ملف مالي لكل شخص، واستلام يُوزَّع تلقائياً على الأقدم، وكشف حساب تُرسله عبر واتساب بضغطة.', 'A financial file for every person, payments split automatically oldest-first, and a statement you send on WhatsApp in one tap.'),
('intro3Title', 'خصوصية كاملة وبداية سهلة', 'Full privacy, easy start'),
('intro3Body', 'بدون حساب أو كلمة مرور، بياناتك على جهازك، والنسخ السحابي اختياري. ثلاث خطوات فقط وتبدأ.', 'No account or password, your data stays on your device, and cloud backup is optional. Just three steps and you are in.'),
('introStepName', 'أدخل اسمك', 'Enter your name'),
('introStepCurrency', 'اختر عملتك', 'Choose your currency'),
('introStepFirstTx', 'أضف أول معاملة', 'Add your first transaction'),
('introSampleShop', 'سوبرماركت', 'Supermarket'),
('introSampleFood', 'طعام', 'Food'),
('introSamplePerson1', 'أحمد علي', 'Ahmed Ali'),
('introSamplePerson2', 'خالد سعيد', 'Khaled Saeed'),
('introSamplePerson3', 'محمد حسن', 'Mohammed Hassan'),
('introSampleReceive', 'استلام 500', 'Received 500'),
('introSampleSplit', 'وُزّع تلقائياً على الأقدم', 'Split oldest-first'),
('introSampleIncome', 'دخل', 'Income'),
('introSampleExpense', 'مصروف', 'Expense'),
('introSampleBalance', 'إجمالي الأرصدة', 'Total balance'),
('introSampleStatement', 'كشف حساب', 'Statement'),
# ---- الملف الشخصي ----
('stepOf', 'الخطوة {current} من {total}', 'Step {current} of {total}'),
('profileTitle', 'عرّفنا بك', 'Tell us about you'),
('profileSubtitle', 'يظهر اسمك في رأس كشوف الحساب والتقارير', 'Your name appears at the top of statements and reports'),
('profileChangeLater', 'يمكنك تغيير الاسم والهاتف لاحقاً من الإعدادات', 'You can change your name and phone later in Settings'),
('yourName', 'الاسم', 'Name'),
('phoneOptional', 'رقم الهاتف (اختياري)', 'Phone number (optional)'),
('phoneHint', '05xxxxxxxx', '05xxxxxxxx'),
('welcomeName', 'مرحباً {name}', 'Welcome, {name}'),
('currencyStepSubtitle', 'الخطوة 2 من 2 — اختر عملة التطبيق', 'Step 2 of 2 — choose the app currency'),
('sectionProfile', 'الملف الشخصي', 'Profile'),
('editProfile', 'تعديل الملف الشخصي', 'Edit profile'),
('addYourName', 'أضف اسمك', 'Add your name'),
('noPhone', 'لم يُضف رقم هاتف', 'No phone number added'),
('greetingName', '{greeting}، {name}', '{greeting}, {name}'),
('issuedBy', 'صادر من: {name}', 'Issued by: {name}'),
]

PLURAL_INT = {'remainingForDays': ['days'], 'dueInDays': ['days'], 'overdueDays': ['days'], 'peopleCount': ['count'], 'overdueCount': ['count']}

def placeholders(key, text):
    """أسماء المتغيرات مثل {amount} (أحرف لاتينية فقط، فالكلمات العربية داخل
    صيغ الجمع مثل =2{يومين} ليست متغيرات)."""
    names = []
    for m in re.finditer(r'\{([A-Za-z_][A-Za-z0-9_]*)[},]', text):
        if m.group(1) not in names:
            names.append(m.group(1))
    return names

def build(lang_index, locale):
    out = {'@@locale': locale}
    keys = set()
    for key, ar, en in S:
        assert key not in keys, key
        keys.add(key)
        text = ar if lang_index == 1 else en
        out[key] = text
        if lang_index == 1:
            ph = {}
            for n in placeholders(key, ar):
                ph[n] = {'type': 'int'} if n in PLURAL_INT.get(key, []) else {'type': 'String'}
            if ph:
                out['@' + key] = {'placeholders': ph}
    return out

base = os.path.join(os.path.dirname(__file__), '..', 'lib', 'l10n')
os.makedirs(base, exist_ok=True)
for idx, loc in [(1, 'ar'), (2, 'en')]:
    with open(os.path.join(base, f'app_{loc}.arb'), 'w', encoding='utf-8') as f:
        json.dump(build(idx, loc), f, ensure_ascii=False, indent=2)
        f.write('\n')
print(f'{len(S)} strings')
