# -*- coding: utf-8 -*-
# =============================================================================
# مصدر نصوص الواجهة بالعربية والإنجليزية.
# شغّل:  python3 tool/strings.py   لتوليد lib/l10n/app_ar.arb و app_en.arb
# ثم flutter gen-l10n (أو أي flutter run/build يولّدها تلقائياً).
# لإضافة نص: أضف سطراً (المفتاح، العربي، الإنجليزي) ثم أعد تشغيل السكربت.
# =============================================================================
import json, re, os

S = [
# ---- عام ----
('appName', 'دفتري', 'Daftari'),
('save', 'حفظ', 'Save'),
('cancel', 'إلغاء', 'Cancel'),
('delete', 'حذف', 'Delete'),
('edit', 'تعديل', 'Edit'),
('confirm', 'تأكيد', 'Confirm'),
('back', 'رجوع', 'Back'),
('apply', 'تطبيق', 'Apply'),
('reset', 'إعادة ضبط', 'Reset'),
('undo', 'تراجع', 'Undo'),
('continueLabel', 'متابعة', 'Continue'),
('optional', 'اختياري', 'Optional'),
('today', 'اليوم', 'Today'),
('yesterday', 'أمس', 'Yesterday'),
('saved', 'تم الحفظ', 'Saved'),
('seeAll', 'عرض الكل', 'See all'),
('note', 'ملاحظة', 'Note'),
('date', 'التاريخ', 'Date'),
('amount', 'المبلغ', 'Amount'),
('account', 'الحساب', 'Account'),
('category', 'الفئة', 'Category'),
('name', 'الاسم', 'Name'),
('phone', 'رقم الجوال', 'Phone'),
('address', 'العنوان', 'Address'),
('comingSoon', 'قريباً', 'Soon'),
('archivedBadge', 'مؤرشف', 'Archived'),
('defaultBadge', 'افتراضي', 'Default'),
('all', 'الكل', 'All'),
('more', 'المزيد', 'More'),
('noResults', 'لا توجد نتائج', 'No results'),
('password', 'كلمة المرور', 'Password'),
('passwordTooShort', '6 أحرف على الأقل', 'At least 6 characters'),
('areYouSure', 'هل أنت متأكد؟', 'Are you sure?'),
# ---- التنقل ----
('navHome', 'الرئيسية', 'Home'),
('navTransactions', 'المعاملات', 'Activity'),
('navDebts', 'الديون', 'Debts'),
('navMore', 'المزيد', 'More'),
# ---- الإعداد الأول ----
('welcomeTitle', 'مرحباً بك في دفتري', 'Welcome to Daftari'),
('welcomeSubtitle', 'لا حساب • لا كلمة مرور • ابدأ فوراً', 'No account • No password • Start now'),
('chooseCurrency', 'اختر عملتك', 'Choose your currency'),
('currencyWarning', 'ستُستخدم في كل التطبيق ولا يمكن تغييرها لاحقاً', 'Used across the app and cannot be changed later'),
('searchCurrency', 'ابحث عن عملة', 'Search currency'),
('cloudBackupOptionalHint', 'اختياري — يمكن تفعيله لاحقاً من الإعدادات', 'Optional — enable it later from settings'),
('confirmCurrencyTitle', 'تأكيد عملة التطبيق', 'Confirm app currency'),
('confirmCurrencyBody', 'ستُسجَّل كل الحسابات والمعاملات والديون بهذه العملة.', 'All accounts, transactions and debts will be recorded in this currency.'),
('confirmCurrencyWarning', 'لا يمكن تغييرها بعد التأكيد', 'It cannot be changed after confirming'),
('confirmAndStart', 'تأكيد والبدء', 'Confirm & start'),
('backAndChange', 'رجوع وتغيير العملة', 'Back & change currency'),
('restoreExisting', 'لديك نسخة احتياطية؟ استعادة', 'Have a backup? Restore'),
# ---- الرئيسية ----
('greetingMorning', 'صباح الخير', 'Good morning'),
('greetingEvening', 'مساء الخير', 'Good evening'),
('totalBalance', 'إجمالي أرصدة الحسابات', 'Total balance'),
('monthIncome', 'دخل الشهر', 'Income'),
('monthExpense', 'مصروف الشهر', 'Expenses'),
('quickExpense', 'مصروف', 'Expense'),
('quickIncome', 'دخل', 'Income'),
('quickTransfer', 'تحويل', 'Transfer'),
('quickDebt', 'دين', 'Debt'),
('monthlyBudget', 'الميزانية الشهرية', 'Monthly budget'),
('budgetOf', '{spent} من {limit}', '{spent} of {limit}'),
('remainingForDays', 'متبقٍ {amount} لـ {days, plural, =0{اليوم} =1{يوم واحد} =2{يومين} few{{days} أيام} many{{days} يوماً} other{{days} يوم}}', '{amount} left for {days, plural, =0{today} =1{1 day} other{{days} days}}'),
('owedToMe', 'لي عند الناس', 'Owed to me'),
('iOwe', 'عليّ للناس', 'I owe'),
('recentTransactions', 'آخر المعاملات', 'Recent'),
('noTransactionsYet', 'لا توجد معاملات بعد. اضغط + لإضافة أول معاملة.', 'No transactions yet. Tap + to add your first one.'),
('hideBalances', 'إخفاء الأرصدة', 'Hide balances'),
# ---- المعاملات ----
('transactionsTitle', 'المعاملات', 'Transactions'),
('searchTransactions', 'ابحث بالاسم أو المبلغ', 'Search by name or amount'),
('addTransaction', 'إضافة معاملة', 'Add transaction'),
('editTransaction', 'تعديل معاملة', 'Edit transaction'),
('typeExpense', 'مصروف', 'Expense'),
('typeIncome', 'دخل', 'Income'),
('typeTransfer', 'تحويل', 'Transfer'),
('typeAdjustment', 'تسوية', 'Adjustment'),
('typeDebtOut', 'حركة دين — خرج', 'Debt movement — out'),
('typeDebtIn', 'حركة دين — دخل', 'Debt movement — in'),
('debtMovement', 'حركة دين', 'Debt movement'),
('fromAccount', 'من حساب', 'From account'),
('toAccount', 'إلى حساب', 'To account'),
('suggestedForCategory', 'مقترح: آخر حساب للفئة', 'Suggested: last used for category'),
('attachReceipt', 'إرفاق إيصال', 'Attach receipt'),
('receiptAttached', 'تم إرفاق الإيصال', 'Receipt attached'),
('removeReceipt', 'إزالة الإيصال', 'Remove receipt'),
('viewReceipt', 'عرض الإيصال', 'View receipt'),
('receiptCamera', 'الكاميرا', 'Camera'),
('receiptGallery', 'المعرض', 'Gallery'),
('chooseCategory', 'اختر فئة', 'Choose a category'),
('deleteTransactionTitle', 'حذف هذه المعاملة؟', 'Delete this transaction?'),
('deleteTransactionBody', '{description} — {amount}\nسيُعاد المبلغ إلى رصيد «{account}» تلقائياً.', '{description} — {amount}\nThe amount will be returned to “{account}” automatically.'),
('transactionDeleted', 'تم حذف المعاملة', 'Transaction deleted'),
('debtMovementHint', 'حركة دين تحرّك الرصيد ولا تُحتسب دخلاً ولا مصروفاً. تُعدَّل من ملف الشخص.', 'A debt movement changes the balance but is not income or expense. Edit it from the person’s profile.'),
('openPersonProfile', 'فتح ملف الشخص', 'Open profile'),
('budgetWarning', 'اقتربت من ميزانية «{category}»: {percent}%', 'Close to the “{category}” budget: {percent}%'),
('budgetExceeded', 'تجاوزت ميزانية «{category}» ({percent}%)', 'Over the “{category}” budget ({percent}%)'),
('filterTitle', 'فلترة المعاملات', 'Filter transactions'),
('period', 'الفترة', 'Period'),
('periodToday', 'اليوم', 'Today'),
('periodWeek', 'هذا الأسبوع', 'This week'),
('periodMonth', 'هذا الشهر', 'This month'),
('periodLast30', 'آخر 30 يوماً', 'Last 30 days'),
('periodLast3Months', 'آخر 3 أشهر', 'Last 3 months'),
('periodYear', 'هذه السنة', 'This year'),
('periodCustom', 'مخصص', 'Custom'),
('periodAll', 'كل الفترات', 'All time'),
('typeAndCategory', 'النوع والفئة', 'Type & category'),
('showDebtMovements', 'إظهار حركات الديون', 'Show debt movements'),
('showDebtMovementsHint', 'تظهر في السجل فقط ولا تدخل في الدخل والمصروف', 'Listed only — not counted as income or expense'),
('sort', 'الترتيب', 'Sort'),
('sortNewest', 'الأحدث أولاً', 'Newest first'),
('sortOldest', 'الأقدم أولاً', 'Oldest first'),
('sortAmountDesc', 'الأعلى مبلغاً', 'Highest amount'),
('sortAmountAsc', 'الأقل مبلغاً', 'Lowest amount'),
('allCategories', 'كل الفئات', 'All categories'),
('summaryIncome', 'دخل {amount}', 'Income {amount}'),
('summaryExpense', 'مصروف {amount}', 'Expense {amount}'),
# ---- الحسابات ----
('accountsTitle', 'الحسابات', 'Accounts'),
('totalActiveAccounts', 'إجمالي الحسابات النشطة', 'Total of active accounts'),
('activeAccountsCount', 'نشطة ({count})', 'Active ({count})'),
('archivedAccountsCount', 'المؤرشفة ({count})', 'Archived ({count})'),
('archivedSince', 'مؤرشف منذ {date}', 'Archived since {date}'),
('addAccount', 'إضافة حساب', 'Add account'),
('editAccount', 'تعديل الحساب', 'Edit account'),
('accountName', 'اسم الحساب', 'Account name'),
('accountType', 'نوع الحساب', 'Account type'),
('openingBalance', 'الرصيد الافتتاحي', 'Opening balance'),
('accountTypeCash', 'نقدي', 'Cash'),
('accountTypeBank', 'بنكي', 'Bank'),
('accountTypeWallet', 'محفظة', 'Wallet'),
('accountTypeSavings', 'توفير', 'Savings'),
('setAsDefault', 'تعيين كافتراضي', 'Set as default'),
('archive', 'أرشفة', 'Archive'),
('unarchive', 'رفع الأرشفة', 'Unarchive'),
('adjustBalance', 'تسوية الرصيد', 'Adjust balance'),
('adjustBalanceHint', 'أدخل الرصيد الفعلي وسيُسجَّل الفرق كمعاملة «تسوية» في السجل.', 'Enter the real balance; the difference is recorded as an “Adjustment”.'),
('actualBalance', 'الرصيد الفعلي', 'Actual balance'),
('archiveTitle', 'أرشفة «{name}»؟', 'Archive “{name}”?'),
('archiveBody', 'لن يظهر في الرئيسية ولا عند إضافة معاملة أو دين جديد. المعاملات السابقة تبقى كما هي وتظهر في التقارير.', 'It will be hidden from home and from new transactions or debts. Past records stay in history and reports.'),
('archiveHasBalance', 'رصيده الحالي {amount}', 'Current balance {amount}'),
('transferBalanceTo', 'تحويل الرصيد إلى', 'Transfer balance to'),
('transferAndArchive', 'تحويل الرصيد ثم الأرشفة', 'Transfer balance & archive'),
('archiveWithoutTransfer', 'أرشفة دون تحويل', 'Archive without transfer'),
('newDefaultAccount', 'الحساب الافتراضي البديل', 'New default account'),
('recalculateBalances', 'إعادة احتساب الأرصدة', 'Recalculate balances'),
('recalculateDone', 'تمت المراجعة — صُحح {count} حساب', 'Audit done — {count} account(s) corrected'),
# ---- الديون ----
('debtsTitle', 'الديون', 'Debts'),
('debtsSubtitle', 'منفصلة عن الدخل والمصروف', 'Separate from income and expenses'),
('tabOwedToMe', 'لي', 'Owed to me'),
('tabIOwe', 'عليّ', 'I owe'),
('newDebt', 'دين جديد', 'New debt'),
('dueInDays', 'يستحق بعد {days, plural, =1{يوم} =2{يومين} few{{days} أيام} many{{days} يوماً} other{{days} يوم}}', 'Due in {days, plural, =1{1 day} other{{days} days}}'),
('overdueDays', 'متأخر {days, plural, =1{يوماً} =2{يومين} few{{days} أيام} many{{days} يوماً} other{{days} يوم}}', 'Overdue {days, plural, =1{1 day} other{{days} days}}'),
('dueToday', 'يستحق اليوم', 'Due today'),
('statusSettled', 'مسدَّد', 'Settled'),
('statusPartial', 'مسدَّد جزئياً', 'Partially paid'),
('statusOpen', 'مفتوح', 'Open'),
('ofTotal', 'من {amount}', 'of {amount}'),
('noDebts', 'لا توجد ديون مسجلة. سجّل ديناً لتتابع ما لك وما عليك.', 'No debts yet. Record one to track what you are owed and what you owe.'),
('directionOwedToMeHint', 'أقرضت / بعت بالآجل', 'I lent / sold on credit'),
('directionIOweHint', 'اقترضت / اشتريت بالآجل', 'I borrowed / bought on credit'),
('person', 'الشخص', 'Person'),
('choosePerson', 'اختر شخصاً', 'Choose a person'),
('fromContacts', 'من جهات الاتصال', 'From contacts'),
('addPerson', 'إضافة شخص', 'Add person'),
('dueDateOptional', 'الاستحقاق (اختياري)', 'Due date (optional)'),
('moneyLeftAccount', 'هل خرج المبلغ من حساب؟', 'Did money leave an account?'),
('moneyEnteredAccount', 'هل دخل المبلغ إلى حساب؟', 'Did money enter an account?'),
('bookOnlyHint', 'أطفئه عند البيع أو الشراء بالآجل (دفتر فقط)', 'Turn off for credit sales/purchases (ledger only)'),
('decreasesBalanceNotExpense', 'ينقص الرصيد — ليس مصروفاً', 'Decreases balance — not an expense'),
('increasesBalanceNotIncome', 'يزيد الرصيد — ليس دخلاً', 'Increases balance — not income'),
('remindBeforeDue', 'ذكّرني قبل الموعد بيوم', 'Remind me a day before'),
('saveDebt', 'حفظ الدين', 'Save debt'),
('editDebt', 'تعديل الدين', 'Edit debt'),
('deleteDebt', 'حذف الدين', 'Delete debt'),
('deleteDebtBody', 'ستُحذف كل دفعاته وحركاته وتعود الأرصدة كما كانت.', 'All its payments and movements will be removed and balances restored.'),
('recordPayment', 'تسجيل دفعة', 'Record payment'),
('paymentFor', 'تسجيل دفعة — {name}', 'Payment — {name}'),
('remainingAmount', 'المتبقي: {amount}', 'Remaining: {amount}'),
('paymentAmount', 'مبلغ الدفعة', 'Payment amount'),
('fullRemaining', 'كامل المتبقي', 'Full remaining'),
('receivedIntoAccount', 'استلمت المبلغ في حساب', 'Received into an account'),
('paidFromAccount', 'دفعت المبلغ من حساب', 'Paid from an account'),
('suggestedCreationAccount', 'مقترح: حساب إنشاء الدين', 'Suggested: the debt’s account'),
('savePayment', 'حفظ الدفعة', 'Save payment'),
('whichDebt', 'الدين', 'Debt'),
('profileOwedToMe', 'المتبقي لي عند {name}', '{name} owes me'),
('profileIOwe', 'المتبقي عليّ لـ {name}', 'I owe {name}'),
('profileSettled', 'لا يوجد متبقٍ — الحساب مسدَّد', 'Nothing remaining — all settled'),
('paidAmount', 'مدفوع {amount}', 'Paid {amount}'),
('totalDebtsAmount', 'إجمالي الديون {amount}', 'Total {amount}'),
('dueOn', 'يستحق {date}', 'Due {date}'),
('statement', 'كشف', 'Statement'),
('timeline', 'الخط الزمني', 'Timeline'),
('paymentReceived', 'دفعة مستلمة', 'Payment received'),
('paymentMade', 'دفعة مدفوعة', 'Payment made'),
('newDebtEntry', 'دين جديد', 'New debt'),
('debtWithNote', 'دين: {note}', 'Debt: {note}'),
('inAccount', 'في {account}', 'to {account}'),
('fromAccountName', 'من {account}', 'from {account}'),
('withoutAccount', 'بدون حساب', 'No account'),
('editPerson', 'تعديل بيانات الشخص', 'Edit person'),
('hidePerson', 'إخفاء من القائمة', 'Hide from list'),
('deletePayment', 'حذف الدفعة', 'Delete payment'),
('deletePaymentBody', 'ستُعكس حركتها على الرصيد ويُعاد حساب حالة الدين.', 'Its balance movement will be reversed and the debt status recalculated.'),
('searchPeople', 'ابحث عن شخص', 'Search people'),
# ---- كشف الحساب ----
('statementTitle', 'كشف حساب — {name}', 'Statement — {name}'),
('outputFormat', 'طريقة الإخراج', 'Output'),
('outputImage', 'صورة', 'Image'),
('outputImageHint', 'للكشف القصير', 'Short statements'),
('outputPdf', 'PDF', 'PDF'),
('outputPdfHint', 'للكشف الطويل', 'Long statements'),
('preview', 'معاينة', 'Preview'),
('whatsapp', 'واتساب', 'WhatsApp'),
('share', 'مشاركة', 'Share'),
('print', 'طباعة', 'Print'),
('closingBalance', 'المتبقي', 'Balance due'),
('statementShareText', 'كشف حساب {name} — دفتري', 'Statement for {name} — Daftari'),
('generatedAt', 'أُنشئ في', 'Generated'),
('noMovementsInPeriod', 'لا توجد حركات في هذه الفترة', 'No movements in this period'),
('description', 'البيان', 'Description'),
('balance', 'الرصيد', 'Balance'),
('dueFromPerson', 'المبلغ المستحق على {name}', 'Amount due from {name}'),
('dueToPerson', 'المبلغ المستحق لـ {name}', 'Amount due to {name}'),
# ---- التقارير ----
('reportsTitle', 'التقارير', 'Reports'),
('income', 'الدخل', 'Income'),
('expense', 'المصروف', 'Expenses'),
('net', 'الصافي', 'Net'),
('incomeVsExpense', 'الدخل مقابل المصروف', 'Income vs expenses'),
('expenseByCategory', 'المصروف حسب الفئة', 'Expenses by category'),
('incomeByCategory', 'الدخل حسب الفئة', 'Income by category'),
('reportsExcludedNote', 'حركات الديون والتسويات والتحويلات مستبعدة من هذه الأرقام.', 'Debt movements, adjustments and transfers are excluded.'),
('monthlyView', 'شهري', 'Monthly'),
('yearlyView', 'سنوي', 'Yearly'),
('reportTitle', 'تقرير دفتري', 'Daftari report'),
('month', 'الشهر', 'Month'),
('shareOfTotal', 'النسبة', 'Share'),
('transactions', 'المعاملات', 'Transactions'),
('type', 'النوع', 'Type'),
('export', 'تصدير', 'Export'),
# ---- الميزانية ----
('budgetTitle', 'الميزانية', 'Budget'),
('spentOfBudget', 'مصروف {month} من الميزانية', '{month} spending vs budget'),
('addBudget', 'إضافة ميزانية', 'Add budget'),
('editBudget', 'تعديل الميزانية', 'Edit budget'),
('budgetLimit', 'سقف الإنفاق الشهري', 'Monthly limit'),
('alertAtPercent', 'التنبيه عند {percent}%', 'Alert at {percent}%'),
('budgetOverBy', 'تجاوزت الميزانية بـ {amount}', 'Over budget by {amount}'),
('legendSafe', 'أقل من 75%', 'Under 75%'),
('legendWarning', '75–99%', '75–99%'),
('legendExceeded', 'تجاوز', 'Over'),
('noBudgets', 'لا توجد ميزانيات. أضف سقفاً لفئة لتتابع إنفاقك.', 'No budgets yet. Add a limit to a category to track spending.'),
('deleteBudget', 'حذف الميزانية', 'Delete budget'),
# ---- الفئات ----
('categoriesTitle', 'الفئات', 'Categories'),
('addCategory', 'إضافة فئة', 'Add category'),
('editCategory', 'تعديل الفئة', 'Edit category'),
('categoryName', 'اسم الفئة', 'Category name'),
('icon', 'الأيقونة', 'Icon'),
('color', 'اللون', 'Color'),
('expenseCategories', 'فئات المصروف', 'Expense categories'),
('incomeCategories', 'فئات الدخل', 'Income categories'),
# ---- الإعدادات ----
('settingsTitle', 'الإعدادات', 'Settings'),
('sectionCurrency', 'العملة', 'Currency'),
('appCurrencyLocked', 'عملة التطبيق (مقفلة)', 'App currency (locked)'),
('addCurrency', 'إضافة عملة جديدة', 'Add a currency'),
('sectionGeneral', 'عام', 'General'),
('defaultAccount', 'الحساب الافتراضي', 'Default account'),
('languageAndAppearance', 'اللغة والمظهر', 'Language & appearance'),
('language', 'اللغة', 'Language'),
('languageArabic', 'العربية', 'العربية'),
('languageEnglish', 'English', 'English'),
('followDevice', 'حسب الجهاز', 'System'),
('theme', 'المظهر', 'Theme'),
('themeLight', 'فاتح', 'Light'),
('themeDark', 'داكن', 'Dark'),
('arabicDigits', 'الأرقام الهندية (١٢٣)', 'Arabic-Indic digits (١٢٣)'),
('sectionSecurityData', 'الأمان والبيانات', 'Security & data'),
('appLock', 'قفل التطبيق بالبصمة / PIN', 'App lock (biometric / PIN)'),
('cloudBackup', 'النسخ السحابي', 'Cloud backup'),
('localBackup', 'تصدير / استيراد ملف محلي', 'Export / import local file'),
('deleteAllData', 'حذف جميع البيانات', 'Delete all data'),
('deleteAllDataBody', 'سيُحذف كل شيء نهائياً وتعود للإعداد الأول. هذه هي الطريقة الوحيدة لتغيير العملة.', 'Everything will be permanently deleted and you will return to setup. This is the only way to change the currency.'),
('sectionManage', 'الإدارة', 'Manage'),
('version', 'الإصدار {version}', 'Version {version}'),
('contactSupport', 'تواصل مع فريق الدعم', 'Contact support'),
('supportWhatsApp', 'واتساب', 'WhatsApp'),
('supportCall', 'اتصال', 'Call'),
('supportInstagram', 'إنستغرام', 'Instagram'),
('linkOpenFailed', 'تعذّر فتح الرابط', "Couldn't open the link"),
# ---- الأمان ----
('lockedTitle', 'دفتري مقفل', 'Daftari is locked'),
('enterPin', 'أدخل رمز PIN', 'Enter your PIN'),
('wrongPin', 'رمز غير صحيح', 'Wrong PIN'),
('useBiometrics', 'استخدام البصمة / الوجه', 'Use biometrics'),
('unlockReason', 'افتح دفتري', 'Unlock Daftari'),
('verifyIdentity', 'تأكيد هويتك', "Verify it's you"),
('deleteAllDataReason', 'تأكيد حذف جميع البيانات', 'Confirm deleting all data'),
('createPin', 'أنشئ رمز PIN من 4 أرقام', 'Create a 4-digit PIN'),
('confirmPin', 'أعد إدخال الرمز للتأكيد', 'Re-enter to confirm'),
('pinMismatch', 'الرمزان غير متطابقين', 'PINs do not match'),
('biometricUnlock', 'الفتح بالبصمة / الوجه', 'Unlock with biometrics'),
('changePin', 'تغيير رمز PIN', 'Change PIN'),
('lockAfterHint', 'يُقفل التطبيق بعد دقيقة من الخروج منه', 'Locks one minute after leaving the app'),
# ---- النسخ الاحتياطي ----
('backupTitle', 'النسخ الاحتياطي', 'Backup'),
('cloudBackupOff', 'النسخ السحابي معطّل', 'Cloud backup is off'),
('cloudBackupOn', 'النسخ السحابي مفعّل', 'Cloud backup is on'),
('cloudBackupHint', 'بحسابك الشخصي، مشفّر، دون خوادم خاصة بالتطبيق', 'Your own account, encrypted, no app servers'),
('storageProvider', 'مزوّد التخزين (حسابك الشخصي)', 'Storage (your personal account)'),
('googleDrive', 'Google Drive', 'Google Drive'),
('iCloud', 'iCloud', 'iCloud'),
('appleDevicesOnly', 'لأجهزة Apple', 'Apple devices'),
('connected', 'متصل', 'Connected'),
('frequency', 'التكرار', 'Frequency'),
('daily', 'يومي', 'Daily'),
('weekly', 'أسبوعي', 'Weekly'),
('monthly', 'شهري', 'Monthly'),
('wifiOnly', 'النسخ عبر Wi-Fi فقط', 'Wi-Fi only'),
('encryptionInfo', 'تشفير النسخة AES-256', 'AES-256 encryption'),
('lastBackup', 'آخر نسخة: {date}', 'Last backup: {date}'),
('neverBackedUp', 'لم تُنسخ بعد', 'Never backed up'),
('backupNow', 'نسخ الآن', 'Back up now'),
('restore', 'استعادة', 'Restore'),
('backupPassword', 'كلمة مرور التشفير', 'Encryption password'),
('backupPasswordHint', 'تحتاجها لاستعادة النسخة على جهاز جديد. لا يمكن استرجاعها إن نسيتها.', 'Needed to restore on a new device. It cannot be recovered if forgotten.'),
('backupDone', 'تم النسخ بنجاح', 'Backup completed'),
('restoreDone', 'تمت الاستعادة بنجاح', 'Restore completed'),
('restoreConfirm', 'ستُستبدل كل البيانات الحالية بمحتوى النسخة. متابعة؟', 'All current data will be replaced by the backup. Continue?'),
('chooseBackup', 'اختر نسخة', 'Choose a backup'),
('exportLocalFile', 'تصدير ملف نسخة مشفّر', 'Export encrypted backup file'),
('importLocalFile', 'استيراد ملف نسخة', 'Import backup file'),
('noCloudBackups', 'لا توجد نسخ في السحابة', 'No cloud backups found'),
# ---- رسائل الأخطاء ----
('errInvalidAmount', 'أدخل مبلغاً أكبر من صفر', 'Enter an amount greater than zero'),
('errEmptyName', 'الاسم مطلوب', 'Name is required'),
('errDuplicateAccountName', 'يوجد حساب بنفس الاسم', 'An account with this name exists'),
('errAccountArchived', 'الحساب مؤرشف — ارفع أرشفته أولاً', 'The account is archived — unarchive it first'),
('errCannotArchiveLast', 'لا يمكن أرشفة آخر حساب نشط', 'You cannot archive the last active account'),
('errMustChooseNewDefault', 'اختر حساباً افتراضياً بديلاً أولاً', 'Choose a new default account first'),
('errSameAccountTransfer', 'اختر حسابين مختلفين للتحويل', 'Choose two different accounts'),
('errCategoryKindMismatch', 'الفئة لا تناسب نوع المعاملة', 'The category does not match the type'),
('errCategoryRequired', 'اختر فئة', 'Choose a category'),
('errDebtMovementReadOnly', 'حركات الديون تُعدَّل من ملف الشخص', 'Debt movements are edited from the person’s profile'),
('errCannotMoveArchived', 'لا يمكن نقل معاملة من حساب مؤرشف أو إليه', 'Cannot move a transaction to or from an archived account'),
('errPaymentExceeds', 'المبلغ أكبر من المتبقي ({amount})', 'Amount exceeds the remaining ({amount})'),
('errDebtSettled', 'هذا الدين مسدَّد بالكامل', 'This debt is fully settled'),
('errDebtAmountBelowPaid', 'لا يمكن أن يقل المبلغ عن المسدَّد ({amount})', 'Amount cannot be less than what was paid ({amount})'),
('errCurrencyLocked', 'العملة مقفلة ولا يمكن تغييرها', 'The currency is locked'),
('errNotOnboarded', 'أكمل الإعداد الأول أولاً', 'Complete setup first'),
('errCategoryInUse', 'الفئة مستخدمة في معاملات ولا يمكن حذفها', 'The category is in use and cannot be deleted'),
('errNotFound', 'العنصر غير موجود', 'Item not found'),
('errBackupDecryption', 'كلمة المرور خاطئة أو الملف تالف', 'Wrong password or corrupted file'),
('errBackupInvalid', 'الملف ليس نسخة دفتري صالحة', 'Not a valid Daftari backup'),
('errNoConnection', 'لا يوجد اتصال — سيُعاد المحاولة لاحقاً', 'No connection — will retry later'),
('errCloudNotAuthorized', 'لم يتم منح الإذن لحساب التخزين', 'Storage account not authorized'),
('errUnexpected', 'حدث خطأ غير متوقع', 'Something went wrong'),
# ---- الإشعارات ----
('notifChannel', 'تذكير الديون', 'Debt reminders'),
('notifTitle', 'تذكير بدين', 'Debt reminder'),
('notifOwedToMe', 'غداً موعد استحقاق {amount} على {name}', '{name} owes you {amount}, due tomorrow'),
('notifIOwe', 'غداً موعد سداد {amount} لـ {name}', 'You owe {name} {amount}, due tomorrow'),
]

PLURAL_INT = {'remainingForDays': ['days'], 'dueInDays': ['days'], 'overdueDays': ['days']}

def placeholders(key, text):
    """أسماء المتغيرات مثل {amount} (أحرف لاتينية فقط، فالكلمات العربية داخل
    صيغ الجمع مثل =2{يومين} ليست متغيرات)."""
    names = []
    for m in re.finditer(r'\{([A-Za-z_][A-Za-z0-9_]*)[},]', text):
        if m.group(1) not in names:
            names.append(m.group(1))
    return names

def build(lang_index, locale):
    out = {'@@locale': locale}
    keys = set()
    for key, ar, en in S:
        assert key not in keys, key
        keys.add(key)
        text = ar if lang_index == 1 else en
        out[key] = text
        if lang_index == 1:
            ph = {}
            for n in placeholders(key, ar):
                ph[n] = {'type': 'int'} if n in PLURAL_INT.get(key, []) else {'type': 'String'}
            if ph:
                out['@' + key] = {'placeholders': ph}
    return out

base = os.path.join(os.path.dirname(__file__), '..', 'lib', 'l10n')
os.makedirs(base, exist_ok=True)
for idx, loc in [(1, 'ar'), (2, 'en')]:
    with open(os.path.join(base, f'app_{loc}.arb'), 'w', encoding='utf-8') as f:
        json.dump(build(idx, loc), f, ensure_ascii=False, indent=2)
        f.write('\n')
print(f'{len(S)} strings')
